// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"knsh/internal/biz"
	"knsh/internal/conf"
	"knsh/internal/data"
	"knsh/internal/server"
	"knsh/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewRealworldRepo(dataData, logger)
	greeterRealworld := biz.NewGreeterRealworld(greeterRepo, logger)
	realworldService := service.NewrealworldService(greeterRealworld, logger)
	httpServer := server.NewHTTPServer(confServer, realworldService, logger)
	grpcServer := server.NewGRPCServer(confServer, realworldService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
